name: hax

on:
  push:

jobs:
  fstar-type-checking:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4

      - name: ⤵ Install and configure hax
        uses: hacspec/hax-actions@main
        with:
          fstar: v2025.10.06
          hax_reference: hax-lib-v0.3.6 

      - run: sudo apt-get install protobuf-compiler

      - name: 🏃 Extract F*
        run: |
          rm -f proofs/fstar/extraction/*.fst*
          ./hax.py extract
      - name: 🏃 Type-check extracted F*
        run: ./hax.py prove

