name: CI
on: [push]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: clippy
      - run: sudo apt-get install protobuf-compiler
      - run: ./check_copyrights.sh
      - run: cargo test --all-features
      - run: cargo clippy --workspace --all-targets --all-features --keep-going -- -D warnings
  msrv:
    name: MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.83.0
          components: clippy
      - run: sudo apt-get install protobuf-compiler
      - run: cargo +1.83.0 build
  crosspoly_i586:
    name: cross test polynomial i586
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - run: wget https://github.com/cross-rs/cross/releases/download/v0.2.5/cross-x86_64-unknown-linux-gnu.tar.gz
      - run: tar xvzf cross-x86_64-unknown-linux-gnu.tar.gz
      - run: chmod u+x cross
      - run: ./cross test --target i586-unknown-linux-gnu polynomial
  crosspoly_i686:
    name: cross test polynomial i686
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - run: wget https://github.com/cross-rs/cross/releases/download/v0.2.5/cross-x86_64-unknown-linux-gnu.tar.gz
      - run: tar xvzf cross-x86_64-unknown-linux-gnu.tar.gz
      - run: chmod u+x cross
      - run: ./cross test --target i686-unknown-linux-gnu polynomial
  crosspoly_aarch64:
    name: cross test polynomial aarch64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - run: wget https://github.com/cross-rs/cross/releases/download/v0.2.5/cross-x86_64-unknown-linux-gnu.tar.gz
      - run: tar xvzf cross-x86_64-unknown-linux-gnu.tar.gz
      - run: chmod u+x cross
      - run: ./cross test --target aarch64-unknown-linux-gnu polynomial
